### ISSUE TITLE
doesn't work with NSMB2 ctpks

### ISSUE THREAD

**Issue by mariomadproductions** [dnasdw/ctpktool#1]
https://drive.google.com/file/d/0B_yBl-184usmLUF3Y3hWVHRZMWM/view?usp=sharing
https://drive.google.com/file/d/0B_yBl-184usmVXc4akFLNnZIZlk/view?usp=sharing

**Comment by dnasdw** [comment]
![cec_icon40x40](https://cloud.githubusercontent.com/assets/2081018/26277738/a1bb0ee4-3dc0-11e7-840f-14b244350442.png)
![cec_icon48x48](https://cloud.githubusercontent.com/assets/2081018/26277739/a716bf3c-3dc0-11e7-9285-7720438f66c2.png)

There is no error.
